[package]
name = "afc_finder"
version = "0.1.0"
edition = "2024"

[dependencies]
idevice = { git = "https://github.com/jkcoxson/idevice", rev = "c10f4da9f1ee510f5c090e75457cd24ecb17c668", features = [
  "crashreportcopymobile",
  "usbmuxd",
  "installation_proxy",
  "afc",
  "house_arrest",
  "mobile_image_mounter",
  "tss",
] }
egui = { version = "0.33" }
egui_logger = { version = "0.9" }
eframe = { version = "0.33", default-features = false, features = [
  "default_fonts",
  "wgpu",
  "glow",
  "wayland",
  "x11",
] }
wgpu = { version = "27", features = ["dx12", "vulkan", "metal", "gles"] }
rfd = { version = "0.15", features = ["gtk3"], default-features = false }
tokio = { version = "1.45", features = ["full"] }
plist = { version = "1.8" }
log = { version = "0.4" }
uuid = { version = "1.16", features = ["v4"] }
mdns = { version = "3" }
futures-util = { version = "0.3" }

[build-dependencies]
reqwest = { version = "0.12", features = ["blocking"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
